### ISSUE TITLE
Add links to target of items

### ISSUE THREAD

**Issue by stevefaulkner** [ThePacielloGroup/WAI-ARIA-Usage#1]
Where the there are items with >0  instances is it possible to add a link to the part of the results page where these instances start? If so, I suggest a heading at the start of each item.

![results list](https://user-images.githubusercontent.com/835859/85282758-3967ad00-b484-11ea-8671-3c3e79ccf36f.png)

**Comment by gezlemon** [comment]
The instances in the summary aren't grouped together in the detail, as each element in the DOM is evaluated and issues written in the detail as they're found to save memory. I can link to the first instance where an issue occurs if you still think that's useful, but it could be confusing as other instances may appear after unrelated issues? The other option would be to group them by issue type in the details section, but that would use a lot of memory on a large DOM with lots of issues.

**Comment by gezlemon** [comment]
I figured out how to group the results so they could be linked without having to retain them in memory. I've updated the source code with the changes.
