### ISSUE TITLE
new aria in html rule: placeholer / aria-placeholder attributes

### ISSUE THREAD

**Issue by scottaohara** [ThePacielloGroup/WAI-ARIA-Usage#12]
2 tests to implement checks for

https://w3c.github.io/html-aria/tests/placeholder-test.html

**Comment by gezlemon** [comment]
Added aria-palceholder as a supported value for input type="number".

Added check for aria-placeholder being used with the placeholder attribute.

**Comment by scottaohara** [comment]
retested and flags 8 issues as expected
