### ISSUE TITLE
dt 

### ISSUE THREAD

**Issue by scottaohara** [ThePacielloGroup/WAI-ARIA-Usage#18]
* [test page](http://stevefaulkner.github.io/HTML5accessibility/tests/ARIA-tests/ARIAinHTML/dt-testcases.html)
* using arc toolkit => send dom to ARIA checker
* returns only partial results

While producing far more errors than the a/href issue I filed, it is still not a complete list of the invalid roles, and the summary information does not print as expected.

**Comment by gezlemon** [comment]
Fixed an uncaught exception error that was causing this issue.

**Comment by scottaohara** [comment]
retested and getting expected results.  closing
