### ISSUE TITLE
need updated flags for figure

### ISSUE THREAD

**Issue by scottaohara** [ThePacielloGroup/WAI-ARIA-Usage#21]
[figure without child figcaption](https://thepaciellogroup.github.io/aria-test-builder/dist/testcases/figurenofigcaption-test.html) - should allow any role.

[figure with child figcaption](https://thepaciellogroup.github.io/aria-test-builder/dist/testcases/figurewithfigcaption-test.html) - should not allow any role.

**Comment by gezlemon** [comment]
Updated rules for figure with and without a figcaption

**Comment by scottaohara** [comment]
retested and confirmed fixed
