### ISSUE TITLE
input type=password returns 3 valid roles

### ISSUE THREAD

**Issue by scottaohara** [ThePacielloGroup/WAI-ARIA-Usage#22]
[test case](https://thepaciellogroup.github.io/aria-test-builder/dist/testcases/input-Password-test.html)
no roles should return as valid

running the bookmarklet it returns
```
3 valid roles.

    1 instance of searchbox
    1 instance of spinbutton
    1 instance of combobox
```

not sure how to make sense of this though, because the json file seems correct
```
"input-password": {
		"nodeName": "input",
		"nativeRole": null,
		"allowedRoles": []
},
```

**Comment by gezlemon** [comment]
Fixed bug with incorrect password mapping

**Comment by scottaohara** [comment]
retested and verified fixed
