### ISSUE TITLE
ARIA checker incorrectly reports element with role="rowgroup" with table parent element as violation 

### ISSUE THREAD

**Issue by jducrot** [ThePacielloGroup/WAI-ARIA-Usage#23]
**Describe the bug**

> A `<thead role="rowgroup">` element with a <table> parent element is flagged as an ARIA violation by the ARIA checker.

**To Reproduce**

Validate a table using the ARC toolkit ARIA checker with the following structure
```
<table>
  <thead role="rowgroup">
    <tr>
      <td></td>
    </tr>
  </thead>
</table>
```

1. Go to 'https://codepen.io/TPG/pen/63455c05bcb7081b59e2b41d59cd323b'
2. Open ARC toolkit
3. Press 'Send DOM to Aria Checker'

**Expected behavior**

As described in the [ARIA rowgroup role description](https://w3c.github.io/aria/#rowgroup), this situation should not be reported as a violation.

**Screenshots**

![arc_toolkit_rowgroup_table_parent](https://user-images.githubusercontent.com/280674/110326887-3f3bf900-7fe7-11eb-8e1c-075f31330cbe.png)

**Version information**

- Browser and version: Chrome v 89.0.4389.72 
- ARC Toolkit version: 4.3.2.0

**Comment by gezlemon** [comment]
Added rules to check for native required parents and children.

The script has been updated, and will be included in the next release of the ARC extension.

**Comment by gezlemon** [comment]
Closing this as this issue has been addressed.
