### ISSUE TITLE
need update to input type=checkbox/radio required states

### ISSUE THREAD

**Issue by scottaohara** [ThePacielloGroup/WAI-ARIA-Usage#24]
the test for `input type=checkebox role=...` returns the correct 4 valid roles.  

however the info returned for required states is inaccurate

on a `input type=checkbox` the menuitemcheckbox or switch roles shouldn't require aria-checked, as they can rely on the input's default checked attribute / state.

also, if using role=button on a checkbox, there needs to be a required aria-pressed state, otherwise role=button should be flagged as an invalid role.

### edit:
a similar issue exists for input type=radio with role=menuitemradio.  the input's default checked attribute / state can be used rather than aria-checked, so that shouldn't throw a required state error

**Comment by gezlemon** [comment]
Added exceptions for menuitemcheckbox on native checkbox and menuitemradio on native radio elements

**Comment by scottaohara** [comment]
confirming updated. closing
