### ISSUE TITLE
flag use of aria-checked on native input type=checkbox

### ISSUE THREAD

**Issue by scottaohara** [ThePacielloGroup/WAI-ARIA-Usage#28]
should flag authors using aria-checked on an input type=checkbox, as the element's default checked attribute / state always wins out anyway

https://w3c.github.io/html-aria/tests/checked-test.html

**Comment by gezlemon** [comment]
Thanks, Scott. I've updated it to test for aria-checked on native radio buttons too.

**Comment by scottaohara** [comment]
confirmed fixed
