### ISSUE TITLE
html and body returned as unknown elements

### ISSUE THREAD

**Issue by scottaohara** [ThePacielloGroup/WAI-ARIA-Usage#30]
run [the test case](https://w3c.github.io/html-aria/tests/body-head-test.html) against the checker.

would expect `role=document` on `body` to be noted as redundant, and any other role to be reported as an error.

any role on `html` should be reported as error

currently it says the body element is unknown:
>Unknown element body has role textbox.

and html
>Unknown element html has role presentation.

**Comment by gezlemon** [comment]
Added rules for html and body elements

**Comment by scottaohara** [comment]
verified updated.  thank you
