### ISSUE TITLE
select with multiple does not return correct results

### ISSUE THREAD

**Issue by scottaohara** [ThePacielloGroup/WAI-ARIA-Usage#31]
[select with multiple attribute](https://thepaciellogroup.github.io/aria-test-builder/dist/testcases/select-2-test.html)
expected result - no allowed roles

currently results indicate `menu` is allowed, which is the expected results for `select` w/out `multiple` or `size` attributes

**Comment by gezlemon** [comment]
Added check for select with size and multiple attributes

**Comment by scottaohara** [comment]
verified updated.  thank you
