### ISSUE TITLE
no role on summary element

### ISSUE THREAD

**Issue by scottaohara** [ThePacielloGroup/WAI-ARIA-Usage#32]
[test case](https://thepaciellogroup.github.io/aria-test-builder/dist/testcases/summaryOpen-test.html)

currently says the button role is valid, but this is no longer allowed.

Note: if the above link breaks, check [this test case](https://thepaciellogroup.github.io/aria-test-builder/dist/testcases/summary-test.html) (which may not work, unless the above is broken).

**Comment by gezlemon** [comment]
Removed button role as allowable on summary elements.

**Comment by scottaohara** [comment]
verified as updated.  thank you
