### ISSUE TITLE
use of aria-required needs updates

### ISSUE THREAD

**Issue by scottaohara** [ThePacielloGroup/WAI-ARIA-Usage#33]
[test cases](https://w3c.github.io/html-aria/tests/required-test.html)

test 1 expects no warnings for use of `aria-required` on elements where the `required` attribute is allowed. presently `date`, `datetime-local`, `month`, `time` and `week` `input`s do not pass the validator.

test 2 expects a warning when `aria-required=true` and `required` are used on the same element. presently only `textarea` and `select` throw a warning for the duplicate use of this attribute.

test 3 expects an error when `aria-required=false` and `required` are used on the same element. presently this is not implemented

**Comment by gezlemon** [comment]
Added tests for aria-required usage

**Comment by scottaohara** [comment]
verified as updated.
