### ISSUE TITLE
updates for aria-valuemax conformance

### ISSUE THREAD

**Issue by scottaohara** [ThePacielloGroup/WAI-ARIA-Usage#34]
[test cases](https://w3c.github.io/html-aria/tests/max-test.html)

[ARIA in HTML `max` / `aria-valuemax`](https://w3c.github.io/html-aria/#att-max)

`input type=number`, `type=range` and `progress` should all report errors to use the `max` attribute instead

**Comment by gezlemon** [comment]
Added tests for aria-valuemax on input type="number" and type="range"

**Comment by scottaohara** [comment]
this update is sufficient for what ARIA in HTML needs, but there were no warnings / errors surfaced for the `progress` element

**Comment by gezlemon** [comment]
Thanks, Scott. Added checks for progress element.

**Comment by scottaohara** [comment]
thanks!
