### ISSUE TITLE
image results

### ISSUE THREAD

**Issue by scottaohara** [ThePacielloGroup/WAI-ARIA-Usage#36]
if an image has no `alt` attribute or has an `alt=""` - it should allow no role.   [test case](https://thepaciellogroup.github.io/aria-test-builder/dist/testcases/img-noalt-test.html)

caveat to the above which is not necessary to implement at this time, but would be nice - if either of the above cases are encountered, and the image has an `aria-label` or `aria-labelledby` then they SHOULD be evaluated against the [`img alt=something` test case](https://thepaciellogroup.github.io/aria-test-builder/dist/testcases/img-test.html)

**Comment by gezlemon** [comment]
Hi @scottaohara , When I run the test case through the validator they are all being flagged as invalid roles (apart from the dpub roles, which I'm working on). Can you provide more information on what the expected result should be?

**Comment by scottaohara** [comment]
hey @gezlemon, running the test case against the wai-aria usage results, it reports 2 valid roles. `none` and `presentation`. but these are redundant to `alt=""`, so they can be reported as warnings.

**Comment by gezlemon** [comment]
Thanks, @scottaohara. I've added rule to distinguish between no alt on an image and null alt text.

**Comment by scottaohara** [comment]
hey @gezlemon 

looks like `img alt=""` was updated, but `img` without an `alt` still returns `none` and `presentation` as allowed roles

**Comment by gezlemon** [comment]
Thanks, Scott. Updated rule so img without alt is not allowed presentation or none roles.

**Comment by scottaohara** [comment]
@gezlemon I think maybe there's a typo or something that got introduced to the script?  no valid or invalid results are showing up for the image test case now.

**Comment by gezlemon** [comment]
Thanks, Scott. I introduced a logic error with the conditional ancestors check. It could do with more testing, but it's now working on test cases I've tried.

**Comment by scottaohara** [comment]
thanks gez
