### ISSUE TITLE
treatment of dpub roles

### ISSUE THREAD

**Issue by scottaohara** [ThePacielloGroup/WAI-ARIA-Usage#37]
running, for example, [this test case](https://thepaciellogroup.github.io/aria-test-builder/dist/testcases/ahref-test.html) - the checker returns 36 non-existent roles (one of them being the junk role we use for a 'control').

these are all the dpub roles used in the test case.  

while it is not expected for authors to use dpub roles on the web, they are valid roles, and in regards to this particular test case, 4 of them are valid for use.

I would request that at minimum dpub roles are not reported as non-existent roles.  Rather, they be reported as likely not recognized on the web.  

ideally, the checker would report valid dpub roles and invalid dpub roles per element as well.  

Where if an element is allowed "any role" then any dpub role would also be valid
Otherwise, only the indicated allowed dpub roles on that element
Otherwise, no dpub roles allowed if "no role" is declared, or neither of the above are true.

**Comment by gezlemon** [comment]
Added rules for DPub. If valid DPub roles are used, included a note they're likely not recognized on the web

**Comment by scottaohara** [comment]
checking this today, verify rules have been updated
