### ISSUE TITLE
td, th, tr allowances when within a table

### ISSUE THREAD

**Issue by scottaohara** [ThePacielloGroup/WAI-ARIA-Usage#38]
when used within a `role=table, grid, treegrid` the `td`, `tr`, and `th` elements should not be allowed any explicitly set role, as that would break the a11y mappings of the table, grid or treegrid.  
[td in role=table](https://thepaciellogroup.github.io/aria-test-builder/dist/testcases/td-table-test.html)
[td in role=grid](https://thepaciellogroup.github.io/aria-test-builder/dist/testcases/td-grid-test.html)
[td in role=treegrid](https://thepaciellogroup.github.io/aria-test-builder/dist/testcases/td-treegrid-test.html)

[tr in role=table](https://thepaciellogroup.github.io/aria-test-builder/dist/testcases/tr-table-test.html)
[tr in role=grid](https://thepaciellogroup.github.io/aria-test-builder/dist/testcases/tr-grid-test.html)
[tr in role=treegrid](https://thepaciellogroup.github.io/aria-test-builder/dist/testcases/tr-treegrid-test.html)

[th in role=table](https://thepaciellogroup.github.io/aria-test-builder/dist/testcases/th-table-test.html)
[th in role=grid](https://thepaciellogroup.github.io/aria-test-builder/dist/testcases/th-grid-test.html)
[th in role=treegrid](https://thepaciellogroup.github.io/aria-test-builder/dist/testcases/th-treegrid-test.html)

expectations:
*  if a `<td>`'s ancestor table element has role=table, grid or treegrid - then no allowed role.
*  if a `<th>`'s ancestor table element has role=table, grid or treegrid - then no allowed role.
*  if a `<tr>`'s ancestor table element has role=table, grid or treegrid - then no allowed role.
* if any use of `cell`, `gridcell`, `row`, `rowheader`, `columnheader` are found on these elements - then those should  produce warnings as being unnecessary

if a td, tr, or th are used within a table with no set role, thus it should be an implicit role=table (regardless of what browser heuristics may do) - then no allowed role
[td within a table testcase](https://thepaciellogroup.github.io/aria-test-builder/dist/testcases/td-test.html)
[th within a table testcase](https://thepaciellogroup.github.io/aria-test-builder/dist/testcases/th-test.html)
[tr within a table testcase](https://thepaciellogroup.github.io/aria-test-builder/dist/testcases/tr-test.html)

If td, tr, or th are used within a table where it's role is overwritten by a role not mentioned above (e.g., role=none, article, etc), then these elements can continue to allow any role.  **the checker already meets this expectation**

**Comment by gezlemon** [comment]
Added check for table, grid, and treegrid ancestors for td, th, and tr

**Comment by scottaohara** [comment]
@gezlemon seems the rules are in place for checking TD within all the scenarios.  but tr and th rules don't currently pass.

**Comment by gezlemon** [comment]
Thanks, Scott. I've rearranged logic for checking required ancestors.

**Comment by scottaohara** [comment]
thank you Gez.  gave this a look today and results are as expected.  thank you
