### ISSUE TITLE
Should warn about aria-haspopup for input role=combobox with list attribute

### ISSUE THREAD

**Issue by scottaohara** [ThePacielloGroup/WAI-ARIA-Usage#39]
https://w3c.github.io/html-aria/#el-input-text-list

>input type=text, search, tel, url, email, or with a missing or invalid type, with a list attribute
    Authors SHOULD NOT use the aria-haspopup attribute on the indicated inputs with a list attribute.
    Otherwise, any global aria-* attributes and any other aria-* attributes applicable to the combobox role.

implementation report has test cases
https://w3c.github.io/html-aria/results/implementation-results.html#el-input-text-list

Currently the wai usage script returns the invalid roles, but doesn't mention the warning for `aria-haspopup`.  additionally, seems there might be a bug in the script as the typical summary/details info isn't displayed

![summary and details info is blank](https://user-images.githubusercontent.com/4152514/118493238-e4153980-b6ee-11eb-842c-5ebbd39ba637.jpg)

**Comment by gezlemon** [comment]
Thanks, @scottaohara 

Do you have a URL for where the summary isn't displaying? I'll track down that bug when I add the warning for aria-haspopup.

**Comment by gezlemon** [comment]
Hi @scottaohara ,

I've added the rules for using aria-haspopup with a native list attribute for the input types you mentioned. I still haven't been able to recreate the bug that stops the summary from displaying.

**Comment by scottaohara** [comment]
thanks gez.

That's odd about the different results.  I went to https://thepaciellogroup.github.io/aria-test-builder/dist/testcases/input-Text-test-list.html and ran the bookmarklet and again got results where the summary wasn't populating, instead going right to the details/invalid roles like the screenshot i have above

**Comment by gezlemon** [comment]
Thanks, Scott. I can see the problem from that URL. I'll track it down and work out what's causing it.

**Comment by gezlemon** [comment]
Fixed in latest version. It turned out to be an uncaught exception where non-existant roles are given to elements that can have any role.

**Comment by scottaohara** [comment]
Hey @gezlemon, taking a look at this today I'm not seeing the warnings for this rule.  could you double check for me that this isn't being suppressed somehow?   Is there a possibility I need to re-add the bookmarklet to my browser for testing?

**Comment by gezlemon** [comment]
Hi @scottaohara I'm not sure why we get different results. When I run the bookmarklet on the test page the warning is the last item in the details section:
![Warning message for aria-haspopup with native list attribute](https://user-images.githubusercontent.com/140129/123519120-44f64100-d6a1-11eb-976a-ed36ecbb76b6.png)
I don't think you need to re-add the bookmarklet, but it could be that it's cached?

**Comment by scottaohara** [comment]
Thanks gez. I’ll futz with this later today to see if I can’t figure out what’s wrong on my end then.

**Comment by scottaohara** [comment]
yup, uninstalling and re-installing got rid of the issue so i'm seeing the update now.  thank you!

**Comment by gezlemon** [comment]
Thanks for confirming, @scottaohara
