### ISSUE TITLE
seemingly incorrect error - link is unnecessary on native a elements

### ISSUE THREAD

**Issue by stevefaulkner** [ThePacielloGroup/WAI-ARIA-Usage#4]
example error:
> link is unnecessary on native `a` elements

```
<a jsname="BKxS1e" class="gyPpGe" role="link" tabindex="0" jsaction="i3viod" 
data-ved="0ahUKEwi1g5zV5bbrAhX3ZxUIHUZpBUEQ67oDCAU">Skip to main content</a>
```

While the statement is correct for `<a href>`, `<a>` without `href` does not have an implicit role defined, refer to https://w3c.github.io/html-aria/#el-a-no-href

**Comment by gezlemon** [comment]
Thanks, Steve. I've included an exception for anchor elements without a href attribute.
