### ISSUE TITLE
Update result for non-lowercase role

### ISSUE THREAD

**Issue by scottaohara** [ThePacielloGroup/WAI-ARIA-Usage#40]
Testing `<p role=button>` the bookmarklet returns: "Element p has non-existent role BUTTON."

This should instead return a warning that not all browsers / AT combinations will properly expose roles that are not written in lower case.

At this point this is largely a bug with ATs as apparently all browsers now allow ARIA roles to be written in any casing.

**Comment by gezlemon** [comment]
Thanks, @scottaohara I've added a warning using your suggested wording.

**Comment by scottaohara** [comment]
thank you gez

**Comment by scottaohara** [comment]
Sorry @gezlemon, one more update along these lines.

`<div role=button aria-expanded=TRUE>` should also produce a similar warning.  This would apply to the following attributes:

- aria-atomic
- aria-autocomplete
- aria-busy
- aria-checked
- aria-current
- aria-disabled
- aria-dropeffect
- aria-expanded
- aria-grabbed
- aria-haspopup
- aria-hidden
- aria-invalid
- aria-live
- aria-modal
- aria-multiline
- aria-multiselectable
- aria-orientation
- aria-pressed
- aria-readonly
- aria-relevant
- aria-required
- aria-selected
- aria-sort

**Comment by scottaohara** [comment]
a test case for the above attribute list
https://w3c.github.io/html-aria/tests/casing-attribute.html

**Comment by gezlemon** [comment]
Thanks, @scottaohara Added check to ensure that attribute values for aria-* are lowercase.

**Comment by scottaohara** [comment]
thank you very much!
