### ISSUE TITLE
update allowances for aria-* attributes on datalist element

### ISSUE THREAD

**Issue by scottaohara** [ThePacielloGroup/WAI-ARIA-Usage#49]
[ARIA in HTML](https://github.com/w3c/html-aria/pull/383) is updating the `datalist` element to no longer allow any `aria-*` attributes.  

In reality specifying global `aria-*` attributes, or attributes which can be used with the implicit `listbox` role have no actual impact on the element or its child options. Due to this, while there appears to be no negative impact for users to specify ARIA attributes on the element, allowing authors to do so also serves no benefit, and this should be called out to them.

[test case](https://w3c.github.io/html-aria/tests/datalist-aria-attrs.html)

**Comment by gezlemon** [comment]
Hi @scottaohara, I added a rule to give a warning if global aria attributes or native 'listitem' aria attributes are provided on a 'datalist' element.

**Comment by gezlemon** [comment]
Hi @scottaohara, yes, all the tests stop after finding an error. It was done to prevent compound errors, as the results become overly verbose.

**Comment by scottaohara** [comment]
gotcha.  do you think the message could indicate that there may be additional attributes to correct for?   Otherwise, it might appear to someone that just the first attribute is in error, and then if they fix that they'd be good to go.

**Comment by gezlemon** [comment]
Thanks, @scottaohara, that's a good idea. I've added a generic message that there may be more issues with the element.
