### ISSUE TITLE
Issue with invalid use of aria-* attributes

### ISSUE THREAD

**Issue by scottaohara** [ThePacielloGroup/WAI-ARIA-Usage#50]
doing some checks related to #49, I noticed that [the link test](https://thepaciellogroup.github.io/aria-test-builder/dist/testcases/link-test.html) was not returning any instances of invalid use of `aria-*` attributes, even though no `aria-*` attributes are allowed on `<link>`.  Is there a bug here?

**Comment by gezlemon** [comment]
Hi @scottaohara I think it's because the links all have invalid roles, so it doesn't get to the aria-* checks.
