### ISSUE TITLE
allowances for aria-expanded corrected in ARIA 1.2

### ISSUE THREAD

**Issue by scottaohara** [ThePacielloGroup/WAI-ARIA-Usage#54]
in aria 1.1, `aria-expanded` was allowed on a number of roles where its usage didn't make sense.  This was corrected in ARIA 1.2 by removing the allowance for the attribute.  This removal wasn't marked as a deprecation, because the attribute wasn't meant to be allowed in the first place.

I will create a PR to remove `aria-expanded` from being allowed on the relevant roles.

**Comment by gezlemon** [comment]
Thanks, @scottaohara
