### ISSUE TITLE
Bug with activedescendant reporting

### ISSUE THREAD

**Issue by scottaohara** [ThePacielloGroup/WAI-ARIA-Usage#57]
In reviewing [this test case](https://w3c.github.io/html-aria/tests/button-combobox.html) after merging in #56, I noticed the following was reported under invalid properties:

>Element button has an aria-* attribute without a value (aria-activedescendant). There may be additional issues with this element.

When a combobox is in the collapsed state, the `aria-activedescendant` attribute is supposed to be set to the empty string. So this particular flagging of the attribute is not correct.

Maybe what could be done here is if `aria-expanded=false`, then the `aria-activedescendant=""` could be ignored.  And if it is in the expanded state, then this check could continue to be run?

**Comment by gezlemon** [comment]
Thanks, @scottaohara I've followed your suggestion and ignore if aria-expanded="false".

**Comment by scottaohara** [comment]
looks good.  thanks gez
