### ISSUE TITLE
Bug with combobox test results

### ISSUE THREAD

**Issue by scottaohara** [ThePacielloGroup/WAI-ARIA-Usage#58]
In reviewing this [test case](https://w3c.github.io/html-aria/tests/button-combobox.html)

The combobox instances return the following error

>Role combobox missing required child role (textbox,listbox,tree,grid,dialog). There may be additional issues with this element.

The ARIA 1.2 combobox pattern does not require this, and it would actually likely result in the accessibility issues that had the working group move away from the ARIA 1.1 pattern.

If this flag remains, it should probably go under a "needs manual review" section, or something to indicate that depending on the version of combobox that is being implemented, this may not apply.

**Comment by gezlemon** [comment]
Thanks, @scottaohara. I've removed the required children requirement for combobox.
