### ISSUE TITLE
Suggested feature: Back to Top link

### ISSUE THREAD

**Issue by beltonTPG** [ThePacielloGroup/WAI-ARIA-Usage#6]
When using the in-page links in the Summary section, I found I had to scroll back to the top manually to use another link, since the results page is an "about:blank" page (Chrome/PC) and the back button doesn't do anything. 
A Back to top link after each section would be very helpful!

**Comment by gezlemon** [comment]
Thank you, Brian, that's a great suggestion. I've added back to the top links.
