### ISSUE TITLE
div as child of dl

### ISSUE THREAD

**Issue by scottaohara** [ThePacielloGroup/WAI-ARIA-Usage#61]
a `div` can be a child of a `dl` for structural grouping / styling purposes. 

While a `div` normally allows for "any role" to be specified, in this context that would be detrimental to the expected accessibility semantics for the `dl > dt ~ dd` relationship.

[ARIA in HTML](https://github.com/w3c/html-aria/pull/403) is being updated to clarify that, as a child of a `dl`, a `div` is only allowed `role=none|presentation`.

**Comment by gezlemon** [comment]
Hi @scottaohara I've added a rule so that a div as a child of dl is only allowed a role of none or presentation.

**Comment by scottaohara** [comment]
confirmed and closing.  thanks!
