### ISSUE TITLE
elements which are prohibited from being named

### ISSUE THREAD

**Issue by scottaohara** [ThePacielloGroup/WAI-ARIA-Usage#62]
With ARIA 1.2 certain roles are prohibited from being named by authors.

[ARIA in HTML](https://github.com/w3c/html-aria/pull/402) has identified the HTML elements which share these roles, and in some cases, have no corresponding ARIA role but too should be prohibited from being named by authors.  The following list of elements should flag an author error if `aria-label` or `aria-labelledby` are specified on them UNLESS a role which allows for naming is also specified.

Many of the following elements map to ([`generic`](https://www.w3.org/TR/wai-aria-1.2/#generic)) or no corresponding role - often which does not adequately support naming from author.  Or, to roles which also explicitly prohibit naming from authors.

[test case](https://w3c.github.io/html-aria/tests/prohibit-names.html)

- a no href 
- abbr
- address
- area no href 
- b 
- bdi
- bdo
- body 
- caption ([`caption`](https://www.w3.org/TR/wai-aria-1.2/#caption))
- cite
- code ([`code`](https://www.w3.org/TR/wai-aria-1.2/#code))
- data 
- del ([`deletion`](https://www.w3.org/TR/wai-aria-1.2/#deletion))
- div 
- em ([`emphasis`](https://www.w3.org/TR/wai-aria-1.2/#emphasis))
- figcaption ([`caption`](https://www.w3.org/TR/wai-aria-1.2/#caption))
- footer (if not scoped to body)
- header (if not scoped to body)
- hgroup 
- i 
- ins ([`insertion`](https://www.w3.org/TR/wai-aria-1.2/#insertion))
- kbd 
- label
- legend
- mark ([`mark`](https://w3c.github.io/aria/#mark))
- p ([`paragraph`](https://www.w3.org/TR/wai-aria-1.2/#paragraph))
- pre 
- q
- rt
- s 
- samp 
- small 
- span 
- strong ([`strong`](https://www.w3.org/TR/wai-aria-1.2/#strong))
- sub ([`subscript`](https://www.w3.org/TR/wai-aria-1.2/#subscript))
- sup ([`superscript`](https://www.w3.org/TR/wai-aria-1.2/#superscript))
- time ([`time`](https://www.w3.org/TR/wai-aria-1.2/#time))
- u 
- var

**Comment by scottaohara** [comment]
awesome.  thank you @gezlemon 

this update definitely gets us on our way here though.   

wondering if there's a way we can change the `a` error to be "`a` without `href`" to make that more clear?

**Comment by gezlemon** [comment]
Hi @scottaohara good point. I've updated the messages for a and area.
