### ISSUE TITLE
figure role allowance update

### ISSUE THREAD

**Issue by scottaohara** [ThePacielloGroup/WAI-ARIA-Usage#63]
[ARIA in HTML](https://github.com/w3c/html-aria/pull/415) is updating to allow the `doc-example` role on the `figure` element when it has a child `figcaption`.  The `doc-example` role inherits from the `figure` role, intended to work similarly but exposed as with a role description of "example" rather than "figure".

**Comment by gezlemon** [comment]
Thanks, @scottaohara I added doc-example as an allowed role for figure.
