### ISSUE TITLE
Further clarification to allowed roles on list items

### ISSUE THREAD

**Issue by scottaohara** [ThePacielloGroup/WAI-ARIA-Usage#64]
[ARIA in HTML](https://github.com/w3c/html-aria/pull/410) is clarifying the allowed roles on `li` elements.
><a>No `role`</a></strong> if the parent list element has an implicit  or explicit `list` role.
>
 >Otherwise, <a><strong>any `role`</strong></a>.
> NOTE: See <a >`ul`</a>, <a >`ol`</a>, or <a>`menu`</a> for allowed roles for list elements.

This update **disallows any role** on an `li` element so long as it is a child of a `ul`, `ol` or `menu` element is exposed as an implicit or explicit role=list.
A role of `listitem` would produce a **warning** for unnecessary use of a redundant role.

However, if the parent `ul`, `ol` or `menu` has had its implicit list role overwritten, then the `li` may have **any role** so long as that role is an allowed role of its ancestor elements.

For example, the following `li` may have a `role=button` specified as the parent list element as a `role=none`
```html
<ul role=none>
  <li role="button" ...>...</li>
</ul>
```

However, as the following `ul` has a `role=menu` specified, the `role=button` is not allowed.  The only allowed roles for the `li` would be `menuitem`, `menuitemcheckbox` or `menuitemradio`.
```html
<ul role=menu>
  <li role=button>...</button>
</ul>
```

similar to the following, as while the `ul` has a `role=none`, it is a child of a `role=tablist`, so therefor the `li` may only have a role that is an expected descendant of a `tablist`.

```html
<div role=tablist>
  <ul role=none>
    <li role=button>...</li>
  </ul>
</div>
```

Finally, even though the following would be flagged for invalid HTML, the `li` is again allowed any role as it is exposed as a `generic` role when not correctly nested within a list element:

```html
<article>
   ....
   <li role=paragraph>...</li>
   ...
</article>
```

Additional [test cases provided here](https://w3c.github.io/html-aria/tests/li-element-roles.html).

**Comment by gezlemon** [comment]
Thanks, @scottaohara Updated to reflect the new rules. I noticed you were using roles from ARIA 1.2 that were not included in the rule set, so I added the following roles:

- blockquote
- caption
- code
- deletion
- emphasis
- generic
- insertion
- meter
- paragraph
- strong
- subscript
- superscript
