### ISSUE TITLE
False "Positive"?

### ISSUE THREAD

**Issue by thierryk** [ThePacielloGroup/WAI-ARIA-Usage#7]
The bookmarklet returns this message

> "Role tab missing required parent role (tablist)."

Can't we have a tablist that is not an ancestor of tabs as long as we use `aria-owns`? As in:

`<div role="tablist" aria-owns="tpw-0-0-t tpw-0-1-t tpw-0-2-t tpw-0-3-t"></div>`

I didn't find mention of this "pattern" in the official specs but on [MDN](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Tab_Role): 

> Elements with the role tab must either be a child of an element with the tablist role, or have their id part of the aria-owns property of a tablist.

PS: thanks Gez for that bookmarklet, that's a very handy tool.

**Comment by gezlemon** [comment]
Thank you for catching this, Thierry. I've added checks for parent/child relationships with aria-owns.
