### ISSUE TITLE
s element mapping update

### ISSUE THREAD

**Issue by scottaohara** [ThePacielloGroup/WAI-ARIA-Usage#71]
[HTML AAM](https://github.com/w3c/html-aam/pull/442) has been updated to map the s element to role=deletion with Chromium and Gecko having implemented this change, and an issue against webkit has been filed for them to do so as well.

ARIA in HTML is being updated https://github.com/w3c/html-aria/issues/466 to reflect this change

Previously any role was allowed for the s element. That is still true but for the fact that like other elements with implicit roles it is now 'not recommended' for devs to use role=deletion on the element since it will already expose that.

The checker can surface this as an unnecessary role, as it does for other elements where their role is redundantly added.

**Comment by gezlemon** [comment]
Thanks, @scottaohara Updated to map the s element to role=deletion.

**Comment by scottaohara** [comment]
thank you @gezlemon
