### ISSUE TITLE
Check for use of aria-hidden paired with hidden=until-found

### ISSUE THREAD

**Issue by scottaohara** [ThePacielloGroup/WAI-ARIA-Usage#76]
ARIA in HTML is updating to indicate that the use of aria-hidden=true on an element that also has the hidden=until-found attribute needs to be treated as a MUST NOT author error.

Using both together means that someone could find the hidden content using a browser in-page search, but the revealed previously hidden content will now be visually hidden, but still inaccessible to people using AT.

e.g., 

```
<p hidden=until-found aria-hidden=true>some content</p>
```

**Comment by gezlemon** [comment]
Hi @scottaohara, apologies it's taken so long to get to this. 

Is there a change required? The validator currently flags using `aria-hidden=true` along with the `hidden` attribute as invalid, which would include using `hidden=until-found`. Is a special case required for `hidden=until-found`?

**Comment by scottaohara** [comment]
the change here is that aria-hidden=true on just a hidden element is an author SHOULD NOT, where as this new update is a MUST NOT for the specific hidden attribute value.

just wanted to raise this in case a distinction wanted to be made.  but if not, then we're good to go.  thanks!
